apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-uploads-folder
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/pv-baru/wordpress"