apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/pv-baru/mysql"